namespace RDR2
{
	public enum eWeaponAttachPoint : int
	{
		Invalid = -1,
		Primary = 0,
		Secondary = 1,
		PistolR = 2,
		MaxHandWeaponAttachPoints = 2,
		PistolL = 3,
		Knife = 4,
		Lasso = 5,
		Thrower = 6,
		Bow = 7,
		BowAlternate = 8,
		Rifle = 9,
		RifleAlternate = 10,
		Lantern = 11,
		TempLantern = 12,
		Melee = 13,
		MaxSyncedWeaponAttachPoints = 13,
		Hip = 14,
		Boot = 15,
		Back = 16,
		Front = 17,
		ShoulderSling = 18,
		LeftBreast = 19,
		RightBreast = 20,
		LeftArmpit = 21,
		RightArmpit = 22,
		LeftArmpitRifle = 23,
		Satchel = 24,
		LeftArmpitBow = 25,
		RightHandExtra = 26,
		LeftHandExtra = 27,
		RightHandAux = 28,
		MaxWeaponAttachPoints = 29,
	}
}
